CoursePanel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('', include('panel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path
from .views import index, courses, HomeworkCreate, HomeworkUpdate, HomeworkDelete,\
    HomeworkAnswers, AnswerScoreUpdate, CourseAsTeacher, ContentCreate, ContentDelete, CourseAsStudnet, HomeworkView,\
    AnswerUpdate, CourseCreate, CourseAddStudent, download_csv_view

urlpatterns = [
    path('', index, name='index'),
    path('courses/', courses, name='courses'),

    path('course/add/', CourseCreate.as_view(), name='course_create'),
    path('course/t/<int:pk>/students/add/', CourseAddStudent.as_view(), name='course_add_student'),

    path('course/t/<int:pk>/', CourseAsTeacher.as_view(), name='course_as_teacher'),
    path('course/t/<int:pk>/homework/add/', HomeworkCreate.as_view(), name='homework_create'),
    path('course/t/<int:pk>/homework/<int:pk2>/update', HomeworkUpdate.as_view(), name='homework_update'),
    path('course/t/<int:pk>/homework/<int:pk2>/delete', HomeworkDelete.as_view(), name='homework_delete'),
    path('course/t/<int:pk>/homework/<int:pk2>/answers', HomeworkAnswers.as_view(), name='homework_answers'),
    path('course/t/<int:pk>/homework/<int:pk2>/answers/download/', download_csv_view, name='answers_download'),
    path('course/t/<int:pk>/homework/<int:pk2>/answers/<int:pk3>/score/change', AnswerScoreUpdate.as_view(), name='homework_answers_update'),
    path('course/t/<int:pk>/content/add', ContentCreate.as_view(), name='content_create'),
    path('course/t/<int:pk>/content/<int:pk2>/delete', ContentDelete.as_view(), name='content_delete'),

    path('course/<int:pk>/', CourseAsStudnet.as_view(), name='course_as_student'),
    path('course/<int:pk>/homework/<int:pk2>/', HomeworkView.as_view(), name='homework_view'),
    path('course/<int:pk>/homework/<int:pk2>/answer/<int:pk3>/update', AnswerUpdate.as_view(), name='answer_update'),
]

panel/models.py
from django.urls import reverse
from django.utils import timezone

from django.db import models
from django.utils.html import strip_tags

from account.models import Account


class Course(models.Model):
    title = models.CharField(max_length=50, blank=False , verbose_name='عنوان کلاس')
    description = models.TextField(blank=True, verbose_name='توضیحات')
    teacher = models.ForeignKey(Account, on_delete=models.CASCADE)  # TODO: set validator
    students = models.ManyToManyField(Account, related_name='%(class)s_requests_created')

    def get_absolute_url(self):
        return reverse('course_as_teacher', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class CourseContent(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    description = models.TextField(blank=True, verbose_name='توضیحات')
    file = models.FileField(upload_to='CourseContents', verbose_name='فایل')  # TODO: need to check
    published_date = models.DateTimeField(default=timezone.now, editable=True)

    def get_absolute_url(self):
        return reverse('course_as_teacher', kwargs={'pk': self.course.pk})

    def __str__(self):
        return self.course.title + '٬ ' + strip_tags(self.description)


class HomeWork(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='درس')
    name = models.CharField(max_length=50, blank=False, verbose_name='نام')
    description = models.TextField(blank=True, verbose_name='توضیحات')
    published_date = models.DateTimeField(auto_now_add=True)
    deadline_date = models.DateTimeField(blank=False, null=False, verbose_name='آخرین مهلت ارسال')

    def get_absolute_url(self):
        return reverse('course_as_teacher', kwargs={'pk': self.course.pk})

    def __str__(self):
        return self.name


class Answer(models.Model):
    answer = models.FileField(upload_to='Answers', null=True, blank=True)  # TODO: need to check
    student = models.ForeignKey(Account, on_delete=models.CASCADE)
    home_work = models.ForeignKey(HomeWork, on_delete=models.CASCADE)
    submitted_date = models.DateTimeField(null=True, blank=True)
    score = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.student.get_full_name() + '_' + self.home_work.name

panel/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404

from notification.models import Notification
from .models import Course, HomeWork, Answer, CourseContent
from .mixins import FormValidMixin, AccessMixin, VideoValidMixin, AccessStudentMixin, AnswerValidMixin, CourseValidMixin,\
    NotificationMixin

from .functions import download_csv

@login_required
def index(request):
    return redirect('courses')


@login_required
def courses(request):
    courses_as_teacher = Course.objects.filter(teacher=request.user)
    courses_as_student = Course.objects.filter(students=request.user)

    notification = Notification.objects.filter(person=request.user).all()

    return render(request, 'panel/courses.html', context={'courses_as_teacher': courses_as_teacher,
                                                          'courses_as_student': courses_as_student,
                                                          'notifications': notification})


class CourseCreate(LoginRequiredMixin, CourseValidMixin, NotificationMixin, CreateView):
    model = Course
    fields = ['title', 'description']
    template_name = 'panel/course_create.html'


class CourseAddStudent(AccessMixin, NotificationMixin, UpdateView):
    model = Course
    fields = ['students']
    template_name = 'panel/course_add_student.html'

    def get_success_url(self):
        return reverse_lazy('course_as_teacher', kwargs={'pk': self.kwargs['pk']})


class CourseAsStudnet(AccessStudentMixin, NotificationMixin, DetailView):
    model = Course
    template_name = 'panel/course_student.html'
    context_object_name = 'course'

    def get_object(self):
        course = Course.objects.get(pk=self.kwargs['pk'])
        return course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['homeworks'] = HomeWork.objects.filter(course=self.object).order_by('-published_date').all()
        context['contents'] = CourseContent.objects.filter(course=self.object).order_by('published_date').all()
        return context


class HomeworkView(AccessStudentMixin, NotificationMixin, DetailView):
    model = HomeWork
    template_name = 'panel/homework_view.html'
    context_object_name = 'homework'

    def get_object(self):
        return HomeWork.objects.get(pk=self.kwargs['pk2'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['course'] = get_object_or_404(Course, pk=self.kwargs['pk'])
        context['homework'] = get_object_or_404(HomeWork, pk=self.kwargs['pk2'])
        submit_none_answers(context['homework'], context['course'])

        context['answer'] = Answer.objects.get(home_work=context['homework'], student=self.request.user)

        context['now'] = timezone.now()
        return context


class AnswerUpdate(AccessStudentMixin, AnswerValidMixin, NotificationMixin, UpdateView):
    model = Answer
    fields = ['answer']

    def get(self, *args, **kwargs):
        return Http404

    def get_success_url(self):
        return reverse_lazy('homework_view', kwargs={'pk': self.kwargs['pk'], 'pk2': self.kwargs['pk2']})

    def get_object(self):
        return Answer.objects.get(pk=self.kwargs['pk3'])


class CourseAsTeacher(AccessMixin, NotificationMixin, DetailView):
    model = Course
    template_name = 'panel/course_teacher.html'
    context_object_name = 'course'

    def get_object(self):
        course = Course.objects.get(pk=self.kwargs['pk'])
        return course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['homeworks'] = HomeWork.objects.filter(course=self.object).order_by('-published_date').all()
        context['contents'] = CourseContent.objects.filter(course=self.object).order_by('published_date').all()
        return context


class HomeworkCreate(AccessMixin, FormValidMixin, NotificationMixin, CreateView):
    model = HomeWork
    fields = ['name', 'description', 'deadline_date']
    template_name = 'panel/create_change_homework.html'


class HomeworkUpdate(AccessMixin, FormValidMixin, NotificationMixin, UpdateView):
    model = HomeWork
    fields = ['name', 'description', 'deadline_date']
    template_name = 'panel/create_change_homework.html'

    def get_object(self):
        return HomeWork.objects.get(pk=self.kwargs['pk2'])


class HomeworkDelete(AccessMixin, DeleteView):
    model = HomeWork

    def get(self, *args, **kwargs):
        return Http404

    def get_success_url(self):
        course_pk = self.kwargs['pk']
        return reverse_lazy('course_as_teacher', kwargs={'pk': course_pk})

    def get_object(self):
        return HomeWork.objects.get(pk=self.kwargs['pk2'])


def submit_none_answers(homework: HomeWork, course: Course):
    answers = Answer.objects.filter(home_work=homework).order_by('-submitted_date').all()
    students_has_answer = [answer.student for answer in answers]
    students = course.students.all()
    for student in students:
        if student not in students_has_answer:
            answer = Answer()
            answer.student = student
            answer.home_work = homework
            answer.submitted_date = None
            answer.answer = None
            answer.save()


class HomeworkAnswers(AccessMixin, NotificationMixin, ListView):
    model = HomeWork
    template_name = 'panel/homework_answers.html'
    context_object_name = 'answers'

    def get_queryset(self):
        self.homework = get_object_or_404(HomeWork, pk=self.kwargs['pk2'])
        return Answer.objects.filter(home_work=self.homework).order_by('-submitted_date').all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = get_object_or_404(Course, pk=self.kwargs['pk'])
        context['homework'] = get_object_or_404(HomeWork, pk=self.kwargs['pk2'])
        submit_none_answers(context['homework'], context['course'])
        return context


class AnswerScoreUpdate(AccessMixin, UpdateView):
    model = Answer
    fields = ['score']

    def get(self, *args, **kwargs):
        return Http404

    def get_success_url(self):
        return reverse_lazy('homework_answers', kwargs={'pk': self.kwargs['pk'], 'pk2': self.kwargs['pk2']})

    def get_object(self):
        return Answer.objects.get(pk=self.kwargs['pk3'])


class ContentCreate(AccessMixin, VideoValidMixin, NotificationMixin, CreateView):
    model = CourseContent
    fields = ['description', 'file']
    template_name = 'panel/create_change_content.html'


class ContentDelete(AccessMixin, DeleteView):
    model = HomeWork

    def get(self, *args, **kwargs):
        return Http404

    def get_success_url(self):
        course_pk = self.kwargs['pk']
        return reverse_lazy('course_as_teacher', kwargs={'pk': course_pk})

    def get_object(self):
        return CourseContent.objects.get(pk=self.kwargs['pk2'])


def download_csv_view(request, pk, pk2):
    answers = Answer.objects.filter(home_work=pk2).all()
    data = download_csv(answers)

    return HttpResponse(data, content_type='text/csv')

panel/templates/panel/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Use this block to set title out side of this file -->
    <title>
        سامانه آموزش
        {% if title %}
            | {{ title }}
        {% else %}
            {% block title %}{% endblock %}
        {% endif %}
    </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Bootstrap 4 RTL -->
    <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
    <!-- Custom style for RTL -->
    <link rel="stylesheet" href="{% static 'dist/css/custom.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Right navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'index' %}" class="nav-link">خانه</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">ارتباط</a>
            </li>
        </ul>

        {#    <!-- SEARCH FORM -->#}
        {#    <form class="form-inline ml-3">#}
        {#      <div class="input-group input-group-sm">#}
        {#        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">#}
        {#        <div class="input-group-append">#}
        {#          <button class="btn btn-navbar" type="submit">#}
        {#            <i class="fas fa-search"></i>#}
        {#          </button>#}
        {#        </div>#}
        {#      </div>#}
        {#    </form>#}

        <!-- Left navbar links -->
        <ul class="navbar-nav mr-auto-navbav">
            {# TODO: Massages and Notifications #}
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                    {% if notifications %}
                        <span class="badge badge-danger navbar-badge">{{ notifications|length }}</span>
                    {% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    {% for notification in notifications %}
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        {{ notification.title }}
                                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">{{ notification.text }}</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                    {% endfor %}
                </div>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% url 'index' %}" class="brand-link">
            <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">سامانه آموزش</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    {% if requset.user.profile_picture %}
                        <img src="{{ requset.user.profile_picture }}" class="img-circle elevation-2" alt="User Image">
                    {% else %}
                        <img src="{% static 'dist/img/user.jpeg' %}" class="img-circle elevation-2" alt="User Image">
                    {% endif %}
                </div>
                <div class="info">
                    <!-- Set username of firstname here -->
                    <a href="#" class="d-block">{{ request.user.first_name }} {{ request.user.last_name }}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="{% url 'index' %}" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                صفحه اصلی
                            </p>
                        </a>
                    </li>
                    <!-- courses -->
                    <li class="nav-item">
                        <a href="{% url 'course_create' %}" class="nav-link">
                            <i class="nav-icon fa fa-pen"></i>
                            <p>
                                تشکیل کلاس جدید
                                <span class="right badge badge-danger">New</span>
                            </p>
                        </a>
                    </li>

                    <!-- Account/ logout.. -->
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fa fa-user"></i>
                            <p>
                                اکانت
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'change_id' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>تغییر شماره دانشجویی</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'logout' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>خروج از حساب کاربری</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">{% block header %}{% endblock %}</h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                {% block main %}
                {% endblock %}
                <br>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        سامانه آموزش.
        طراحی و توسعه توسط
        <b>محمد ابراهیمی</b>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

{##}
{##}
{#<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>#}
{#<!-- Bootstrap 4 -->#}
{#<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>#}
{#<!-- Select2 -->#}
{#<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>#}
{#<!-- Bootstrap4 Duallistbox -->#}
{#<script src="{% static 'plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>#}
{#<!-- InputMask -->#}
{#<script src="{% static 'plugins/inputmask/jquery.inputmask.bundle.js' %}"></script>#}
{#<script src="{% static 'plugins/moment/moment.min.js' %}"></script>#}
{#<!-- date-range-picker -->#}
{#<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>#}
{#<!-- bootstrap color picker -->#}
{#<script src="{% static 'plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js' %}"></script>#}
{#<!-- Tempusdominus Bootstrap 4 -->#}
{#<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>#}
{#<!-- AdminLTE App -->#}
{#<script src="{% static 'dist/js/adminlte.min.js' %}"></script>#}
{#<!-- AdminLTE for demo purposes -->#}
{#<script src="{% static 'dist/js/demo.js' %}"></script>#}
{#<!-- Page script -->#}
{##}
{#<script>#}
{#    $(function () {#}
{#        //Initialize Select2 Elements#}
{#        $('.select2').select2({#}
{#            theme: 'bootstrap4'#}
{#        })#}
{##}
{#        //Date range picker with time picker#}
{#        $('#reservationtime').daterangepicker({#}
{#            timePicker: true,#}
{#            timePickerIncrement: 30,#}
{#            locale: {#}
{#                format: 'MM/DD/YYYY hh:mm'#}
{#            }#}
{#        })#}
{##}
{#    })#}
{#</script>#}
{##}



</body>
</html>

panel/templates/panel/homework_view.html
{% extends 'panel/base.html' %}

{% block title %}| {{ course.title }}{% endblock %}

{% block main %}
    <!-- header for introducing course: course name, description, teacher -->
    <div class="card card-primary">
        <!-- /.card-header -->
        <!-- form start -->
        <div class="card-body">
            <h1 class="m-0 text-dark">{{ homework.name }}</h1>
            <br>
            {{ homework.description|safe }}
            <br>
            <br>
            <p>مهلت ارسال: {{ homework.deadline_date }}</p>

            {% if homework.deadline_date > now %}
                <form method="POST" enctype="multipart/form-data" action="{% url 'answer_update' course.pk homework.pk answer.pk%}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <button type="submit" class="btn btn-danger btn-sm">ارسال فایل</button>
                        </div>
                        <!-- /btn-group -->
                        <input type="file" name="answer" id="id_answer" class="form-control">
                    </div>
                </form>
            {% else %}
                <h1 class="badge badge-danger">مهلت ارسال تمام شده است</h1>
            {% endif %}
        </div>
        <!-- /.card-body -->
    </div>

    {% if answer.answer %}
        <h4 class="mb-2 mt-4">پاسخ ارسالی قبلی</h4>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">

                            <tbody>


                            <tr>
                                <td>
                                    {% if answer.score %}
                                        نمره:
                                        {{ answer.score }}
                                    {% else %}
                                        نمره ای ثبت نشده است
                                    {% endif %}
                                </td>
                                <td>{{ answer.submitted_date }}</td>

                                <td>
                                    <a href="{{ answer.answer.url }}" target="_blank" type="button" class="btn btn-block btn-success btn-sm"><i class="fa fa-download"></i></a>
                                </td>
                            </tr>


                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    {% endif %}
{% endblock %}